### ISSUE TITLE
Issue with UTF-8 characters in messages

### ISSUE THREAD

**Issue by markus82** [techthoughts2/PoshGram#19]
I recognized an issue with UTF-8 characters in the messages
As example in the function Send-TelegramTextMessage

Send-TelegramTextMessage -BotToken $Alarm_Token -ChatID $Alarm_Chatids -Message "Testmessage UTF8 Hallö" -verbose

VERBOSE: Sending message...
VERBOSE: POST https://api.telegram.org/bot{Token}/sendMessage with 141-byte payload
VERBOSE: received 88-byte response of content type application/json
WARNING: An error was encountered sending the Telegram message:
Send-TelegramTextMessage : {"ok":false,"error_code":400,"description":"Bad Request: text must be encoded in UTF-8"}

According to my analysis it can be fixed as follows, to convert the Body to UTF-8
(all functions with text messages)
Current code:
    try {
        Write-Verbose -Message "Sending message..."
        $results = Invoke-RestMethod `
            -Uri ("https://api.telegram.org/bot{0}/sendMessage" -f $BotToken) `
            -Method Post `
            -ContentType "application/json" `
            -Body (ConvertTo-Json -Compress -InputObject $payload) `
            -ErrorAction Stop
    }#try_messageSend

Fixed code:
   try {
        Write-Verbose -Message "Sending message..."
		$results = Invoke-RestMethod `
            -Uri ("https://api.telegram.org/bot{0}/sendMessage" -f $BotToken) `
            -Method Post `
            -ContentType "application/json" `
            -Body ([System.Text.Encoding]::UTF8.GetBytes((ConvertTo-Json -Compress -InputObject $payload))) `
            -ErrorAction Stop
    }#try_messageSend

**Comment by techthoughts2** [comment]
Error duplicated:

```
Send-TelegramTextMessage : {"ok":false,"error_code":400,"description":"Bad Request: text must be encoded in UTF-8"}
At line:1 char:1
+ Send-TelegramTextMessage -BotToken $token -ChatID $channel -Message ' ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Send-TelegramTextMessage
```

**Comment by techthoughts2** [comment]
Thanks @markus82 for reporting the issue - much appreciated
