### ISSUE TITLE
PoshBot integration

### ISSUE THREAD

**Issue by mvanders** [techthoughts2/PoshGram#30]
I’m looking to implement PoshBot, but we would like to use Telegram as the chat platform backend. How difficult would it be to make PoshBot work with Telegram using PshGram?

Anyhow, as I’m really impressed with PoshGram from your video on youtube!

Grts,
Marc Vanderstraeten
mv@acea.be

**Comment by techthoughts2** [comment]
Hello @mvanders - thanks for you kind words.

I am not familiar enough with PoshBot to estimate the level of effort required to integrate with it.

I see that you have opened an issue on the PoshBot repo here: https://github.com/poshbotio/PoshBot/issues/187

As there isn't any direct action to be taken right now on the PoshGram side I am going to close this issue out.

If PoshBot integration is possible it can be driven from that tagged issue.
