### ISSUE TITLE
Help framing inline keyboard button

### ISSUE THREAD

**Issue by pkarunkar** [techthoughts2/PoshGram#43]
Hi, I am new to bot coding. I am using this module and it works great when I send text message.
But I am not able to understand how to frame complex url like keyboard buttons, inline button  , async methods... 

Can someone provide code snippets on how to achieve this? Please.

**Comment by techthoughts2** [comment]
This capability is now included in v1.16.0 of PoshGram.

I have added examples to the help for Send-TelegramTextMessage.

I have also added [documentation for sending keyboards](https://github.com/techthoughts2/PoshGram/blob/master/docs/PoshGram-FAQ.md#how-can-i-send-properly-formed-keyboards) in the FAQ.
