### ISSUE TITLE
Send-TelegramPoll - Now allows first option.

### ISSUE THREAD

**Issue by puzatiy** [techthoughts2/PoshGram#50]
There is an issue with the function "Send-TelegramPoll". (PoshGram/src/PoshGram/Public/Send-TelegramPoll.ps1)
Line 238 has the wrong if statement.

### Expected Behavior

($null -eq $QuizAnswer -or $QuizAnswer -lt 0 -or $QuizAnswer -gt 10)
Poll answers are starting from 0. [Telegram API > Poll](https://core.telegram.org/bots/api#poll)

### Current Behavior

($null -eq $QuizAnswer -or $QuizAnswer -lt 1 -or $QuizAnswer -gt 10)

### Possible Solution

To change 1 to 0.

### Steps to Reproduce

1. To send a telegram poll where the answer is the first option. (Which means $QuizAnswer = 0)

**Comment by techthoughts2** [comment]
Reproduced bug. 🐛 

```
0-based identifier of the correct answer option, required for polls in quiz mode
```

Working on a fix.
