### ISSUE TITLE
PoshGram not sending message

### ISSUE THREAD

**Issue by miltontom** [techthoughts2/PoshGram#55]
The message was sent successfully when I first exectuted, again executing gives me the error. It's the same with when I test with  `Test-BotToken`
* powershell version 7.4.1
* PoshGram version 2.3.0

![Screenshot 2024-05-21 194234](https://github.com/techthoughts2/PoshGram/assets/83508961/359cef8b-0095-4de3-9998-a1c585cf8171)

**Comment by miltontom** [comment]
I updated the module to latest version, but still not working...

**Comment by techthoughts2** [comment]
I am unable to reproduce this issue on my workstation or in infra tests.
No other users are reporting an issue.

Are you still experiencing an issue?

If so, can you try running with `-Verbose` and `-Debug` switches?

```
Send-TelegramTextMessage -BotToken $token -ChatID $channel -Message "hello world" -Verbose -Debug
```

![image](https://github.com/techthoughts2/PoshGram/assets/14536775/9674f75a-a4d6-4388-830e-87870f0cbb7a)
